### ISSUE TITLE
Begin/end?

### ISSUE THREAD

**Issue by kristofer** [rochus-keller/Luon#2]
I’ve studied your Som work for a while now. I think Luon an intriguing idea.

please, why use begin/end as block keywords? Just the pascal -> Oberon precedent? Or another reason?

many thanks,

**Comment by rochus-keller** [comment]
Personally I prefer begin/end to {}, though I can live with both. My approach to language design is "evolution, not revolution". Pascal descentants are mostly LL(1) which makes it easier to implement compilers compared to e.g. C++. Modula-2 and Oberon were significant improvements over the Pascal syntax (e.g. no dangling else, each control structure is a block, etc.), and Lua syntax is pretty similar to Modula-2 and Oberon. So it is natural to use begin/end in Luon, as I already did in Oberon+.

**Comment by kristofer** [comment]
yes, and admission: i'd forgotten about the 'end' in Lua...

I'm looking forward to spending some time building with it. 

Cheers, Kristofer

**Comment by rochus-keller** [comment]
Lua re-used a lot of syntax from Modula-2.
