### ISSUE TITLE
Error when starting build.lua script

### ISSUE THREAD

**Issue by MarcusE1W** [rochus-keller/Luon#3]
ArchLinux on Aarch64

When I start the build script
> ./lua build.lua ../Luon
I get this error:

```
luon/build>  ./lua build.lua ../Luon
# Hello from BUSY version 2023-05-10
# running parser
# root source directory is //home/mmw/.local/git/luon/Luon
//home/mmw/.local/git/luon/Luon:ERR: this is not a valid BUSY module!
```

I could not compile the LuaJit compiler, however version 2.1.17 is already installed, not sure if that is relevant for this.

**Comment by rochus-keller** [comment]
You "luon/build" directory seems to be in the directory "/home/mmw/.local/git", which doesn't seem to work for some reason. Can you follow the build instruction and just use a normal root directory and unzip all compressed source files there as described in the instructions?

LuaJIT 2.1 is not compatible. The IDE requires the special LuaJIT 2.0 version referenced in the build instructions, otherwise the debugger won't work.

**Comment by MarcusE1W** [comment]
I am now using this script from my root directory, same error.
From the LuaJit docu I suspect that ARM64  (aarch64) is not supported by thet LuaJit version, only ARM32.
( from `luon/LuaJIT/doc/install.html`)

```
#!/bin/sh -

mkdir luon
cd luon

# Oberon
wget https://github.com/rochus-keller/Luon/archive/refs/heads/master.zip .
unzip master.zip
mv Luon-master Oberon
rm *.zip

# LuaJIT
wget https://github.com/rochus-keller/LuaJIT/archive/refs/heads/LjTools.zip .
unzip LjTools.zip
mv LuaJIT-LjTools LuaJIT
rm *.zip

# MonoTools
wget https://github.com/rochus-keller/LjTools/archive/refs/heads/master.zip .
unzip master.zip
mv LjTools-master MonoTools
rm *.zip

# GuiTools
wget https://github.com/rochus-keller/GuiTools/archive/refs/heads/master.zip .
unzip master.zip
mv GuiTools-master GuiTools
rm *.zip

# LeanQt
wget https://github.com/rochus-keller/LeanQt/archive/refs/heads/master.zip .
unzip master.zip
mv LeanQt-main LeanQt
rm *.zip

# build
wget https://github.com/rochus-keller/BUSY/archive/refs/heads/master.zip .
unzip master.zip
mv BUSY-main build
rm *.zip

# compile Lua
cd build
cc *.c -O2 -lm -o lua

# build Luon
./lua build.lua ../Luon
```

**Comment by rochus-keller** [comment]
Ok, I found the issue when I run your script on my machine; there is a mistake in the build description; instead of "Luon", the decription says that the directory should be called "Oberon"; this is a copy/paste error which I'm going to fix immediately; sorry for inconvenience; hope it works now.

**Comment by MarcusE1W** [comment]
With these changes it the build.lua script start now. Thanks :-)

Here is the updated version of my script to set everything up:
```
#!/bin/sh -

mkdir luon-build
cd luon-build

# Luon
wget https://github.com/rochus-keller/Luon/archive/refs/heads/master.zip .
unzip master.zip
mv Luon-master Luon
rm *.zip

# LuaJIT
wget https://github.com/rochus-keller/LuaJIT/archive/refs/heads/LjTools.zip .
unzip LjTools.zip
mv LuaJIT-LjTools LuaJIT
rm *.zip

# LjTools
wget https://github.com/rochus-keller/LjTools/archive/refs/heads/master.zip .
unzip master.zip
mv LjTools-master LjTools
rm *.zip

# GuiTools
wget https://github.com/rochus-keller/GuiTools/archive/refs/heads/master.zip .
unzip master.zip
mv GuiTools-master GuiTools
rm *.zip

# LeanQt
wget https://github.com/rochus-keller/LeanQt/archive/refs/heads/master.zip .
unzip master.zip
mv LeanQt-main LeanQt
rm *.zip

# build
wget https://github.com/rochus-keller/BUSY/archive/refs/heads/master.zip .
unzip master.zip
mv BUSY-main build
rm *.zip

# compile Lua
cd build
cc *.c -O2 -lm -o lua

# build Luon
./lua build.lua ../Luon

```

**Comment by MarcusE1W** [comment]
Thanks for the help. done now,

**Comment by rochus-keller** [comment]
Glad to hear. Are you working on a Raspi? Did building and linking with LuaJIT work well?

**Comment by MarcusE1W** [comment]
I am using a Pinebook Pro as my private laptop. Sometimes a bit slower, but works ok.
The same error about vsnprintf as when I compiled Oberon+ came up in LeanQt, but that is unrelated to this issue.

From the documentation that comes with the LuaJIT download package I suspect that ARM64 or Aarch64 might be not supported in that version of LuaJIT, but I will dig a bit more into that.
